"""
Configuration Management with Environment Variables
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Load .env file
env_path = Path('.') / '.env'
load_dotenv(dotenv_path=env_path)

class Config:
    """Central configuration class"""
    
    # API Keys
    SHODAN_API_KEY = os.getenv('SHODAN_API_KEY', '')
    VIRUSTOTAL_API_KEY = os.getenv('VIRUSTOTAL_API_KEY', '')
    CENSYS_API_ID = os.getenv('CENSYS_API_ID', '')
    CENSYS_API_SECRET = os.getenv('CENSYS_API_SECRET', '')
    HUNTER_API_KEY = os.getenv('HUNTER_API_KEY', '')
    SECURITYTRAILS_API_KEY = os.getenv('SECURITYTRAILS_API_KEY', '')
    
    # Tool Settings
    MAX_THREADS = int(os.getenv('MAX_THREADS', '10'))
    REQUEST_TIMEOUT = int(os.getenv('REQUEST_TIMEOUT', '30'))
    USER_AGENT_ROTATION = os.getenv('USER_AGENT_ROTATION', 'true').lower() == 'true'
    WAF_DETECTION = os.getenv('WAF_DETECTION', 'true').lower() == 'true'
    
    # Rate Limits (Free Tier Compliance)
    RATE_LIMITS = {
        'virustotal': 4,      # 4 requests per minute
        'shodan': 60,         # 60 requests per minute
        'hunter': 10,         # 10 requests per minute
        'censys': 120,        # 120 requests per minute
        'securitytrails': 50  # 50 requests per minute
    }
    
    # WAF Signatures
    WAF_SIGNATURES = {
        'Cloudflare': ['cf-ray', '__cfduid', 'cf-cache-status'],
        'AWS WAF': ['x-amzn-RequestId', 'aws-waf-token'],
        'Google Cloud Armor': ['x-cloud-trace-context', 'x-goog-'],
        'Imperva': ['x-iinfo', 'x-cdn'],
        'Akamai': ['x-akamai-transformed', 'x-akamai-request-id'],
        'Sucuri': ['x-sucuri-id', 'x-sucuri-cache'],
        'ModSecurity': ['mod_security', 'This error was generated by Mod_Security']
    }
    
    # User-Agent Pool (Real Browsers)
    USER_AGENTS = [
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0',
        'Mozilla/5.0 (iPhone; CPU iPhone OS 17_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Mobile/15E148 Safari/604.1',
        'Mozilla/5.0 (iPad; CPU OS 17_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Mobile/15E148 Safari/604.1',
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0'
    ]
    
    @classmethod
    def validate_api_keys(cls):
        """Check which APIs are configured"""
        available = []
        missing = []
        
        if cls.SHODAN_API_KEY:
            available.append('Shodan')
        else:
            missing.append('Shodan')
            
        if cls.VIRUSTOTAL_API_KEY:
            available.append('VirusTotal')
        else:
            missing.append('VirusTotal')
            
        if cls.CENSYS_API_ID and cls.CENSYS_API_SECRET:
            available.append('Censys')
        else:
            missing.append('Censys')
            
        if cls.HUNTER_API_KEY:
            available.append('Hunter.io')
        else:
            missing.append('Hunter.io')
            
        return available, missing
